# Generated by Django 5.2.7 on 2025-10-10 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Romance', 'Romance'), ('Sci-Fi', 'Sci-Fi'), ('Horror', 'Horror'), ('Slice of Life', 'Slice of Life')], max_length=50)),
                ('rating', models.FloatField(default=0.0)),
                ('synopsis', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='anime_images/')),
                ('release_year', models.IntegerField(default=2024)),
            ],
        ),
    ]
