# Generated by Django 5.2.7 on 2025-10-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anime',
            name='image',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
